export const MARK_NOTIFICATIONS_BY_ID = "MARK_NOTIFICATIONS_BY_ID";
export const MARK_NOTIFICATIONS_ALL = "MARK_NOTIFICATIONS_ALL";
export const START_NOTIFICATIONS = "START_NOTIFICATIONS";
export const END_NOTIFICATIONS = "END_NOTIFICATIONS";
export const GET_NOTIFICATIONS_DATA = "GET_NOTIFICATIONS_DATA";
